spring:
  datasource:
    url: jdbc:postgresql://${APP_POSTGRES_HOST}:${APP_POSTGRES_PORT}/${APP_POSTGRES_DATABASE}
    username: ${APP_POSTGRES_USERNAME}
    password: ${APP_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    show-sql: true

server:
  port: ${APP_PORT}
