#!/usr/bin/env bash

set -e

BL_USERNAME=$APP_POSTGRES_USERNAME
BL_PASSWORD=$APP_POSTGRES_PASSWORD
BL_DATABASE=$APP_POSTGRES_DATABASE

psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "postgres" <<-EOSQL
	CREATE DATABASE $BL_DATABASE;
  CREATE USER $BL_USERNAME WITH PASSWORD '$BL_PASSWORD';
  GRANT ALL PRIVILEGES ON DATABASE $BL_DATABASE TO $BL_USERNAME;
EOSQL

psql -v ON_ERROR_STOP=1 --username "postgres" --dbname "$BL_DATABASE" <<-EOSQL
    GRANT USAGE, CREATE ON SCHEMA public TO $BL_USERNAME;
EOSQL